# Generated by Django 6.0.3 on 2026-05-07 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Tashkilotchi'),
        ),
        migrations.AddField(
            model_name='meetingattendance',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='projects.meeting', verbose_name='Uchrashuv'),
        ),
        migrations.AddField(
            model_name='meetingattendance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(related_name='meeting_participants', through='projects.MeetingAttendance', to=settings.AUTH_USER_MODEL, verbose_name='Qatnashuvchilar'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi'),
        ),
        migrations.AddField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(blank=True, limit_choices_to={'roles__contains': ['employee']}, related_name='employee_projects', to=settings.AUTH_USER_MODEL, verbose_name='Xodimlar'),
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles__contains': ['manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_projects', to=settings.AUTH_USER_MODEL, verbose_name='Menejer'),
        ),
        migrations.AddField(
            model_name='project',
            name='testers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'roles__overlap': ['employee']}, related_name='tester_projects', to=settings.AUTH_USER_MODEL, verbose_name='Sinovchilar'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='projects.project', verbose_name='Loyiha'),
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles__contains': ['employee']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Topshiruvchi'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi'),
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='applications.position', verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='projects.project', verbose_name='Loyiha'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='projects.task', verbose_name='Vazifa'),
        ),
        migrations.AddField(
            model_name='taskrejectionfile',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_files', to='projects.task', verbose_name='Vazifa'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingattendance',
            unique_together={('user', 'meeting')},
        ),
    ]
