# Generated by Django 6.0.3 on 2026-05-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan vaqt'),
        ),
    ]
