# Generated by Django 6.0.3 on 2026-05-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_meeting_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilganmi?"),
        ),
    ]
