# Generated by Django 6.0.3 on 2026-05-09 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_meeting_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingattendance',
            name='absence_reason',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Kela olmaganlik sababi'),
        ),
    ]
