# Generated by Django 6.0.3 on 2026-05-10 05:42

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_meeting_created_at_alter_meeting_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(upload_to='tasks/files/', validators=[apps.common.validators.validate_file_size], verbose_name='Fayl'),
        ),
    ]
