# Generated by Django 6.0.3 on 2026-04-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_meeting_uid_task_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='uid',
            field=models.CharField(editable=False, max_length=7, unique=True, verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='uid',
            field=models.CharField(editable=False, max_length=7, unique=True, verbose_name='UID'),
        ),
    ]
