# Generated by Django 6.0.3 on 2026-05-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projectdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdocument',
            name='url',
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='value',
            field=models.CharField(default=0, max_length=255, verbose_name='Qiymati'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
    ]
