# Generated by Django 6.0.3 on 2026-04-15 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_meeting_uid_alter_task_uid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(limit_choices_to={'roles__contains': ['employee']}, related_name='employee_projects', to=settings.AUTH_USER_MODEL, verbose_name='Xodimlar'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'roles__contains': ['manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_projects', to=settings.AUTH_USER_MODEL, verbose_name='Menejer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles__contains': ['employee']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Topshiruvchi'),
        ),
    ]
