# Generated by Django 6.0.3 on 2026-04-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_employees_alter_project_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='payroll_processed',
            field=models.BooleanField(default=False, verbose_name="Oylik to'landimi?"),
        ),
        migrations.AddField(
            model_name='task',
            name='payroll_processed',
            field=models.BooleanField(default=False, verbose_name="Oylik to'landimi?"),
        ),
    ]
