# Generated by Django 6.0.3 on 2026-04-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_payroll_processed_task_payroll_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingattendance',
            name='payroll_processed',
            field=models.BooleanField(default=False, verbose_name='Oylikda hisoblandimi?'),
        ),
    ]
