# Generated by Django 5.2.12 on 2026-09-12 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_meeting_link_meeting_recording_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='projects.project', verbose_name='Loyiha'),
        ),
    ]
