# Generated by Django 6.0.3 on 2026-04-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_meetingattendance_payroll_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='penalty_percentage',
        ),
    ]
