# Generated by Django 5.2.12 on 2026-09-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_alter_meeting_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="requires_approval",
            field=models.BooleanField(
                default=False, verbose_name="Mezbon tasdig'i talab qilinsinmi?"
            ),
        ),
    ]
