# Generated by Django 5.2.12 on 2026-09-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_meeting_requires_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavfsifi'),
        ),
    ]
