# Generated by Django 5.2.12 on 2026-09-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_alter_meeting_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingattendance",
            name="late_minutes",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Kechikkan vaqti (daqiqa)"
            ),
        ),
    ]
