# Generated by Django 6.0.3 on 2026-04-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_project_testers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
    ]
