# Generated by Django 6.0.3 on 2026-04-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_task_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='uid',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True, verbose_name='UID'),
        ),
    ]
