# Generated by Django 6.0.3 on 2026-04-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_project_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilganmi?"),
        ),
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilganmi?"),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Qilinishi kerak'), ('in_progress', 'Jarayonda'), ('overdue', "Muddati o'tgan"), ('done', 'Bajarildi'), ('production', 'Ishga tushirildi'), ('checked', 'Tekshirildi'), ('rejected', 'Rad etildi')], db_index=True, default='todo', max_length=20, verbose_name='Holati'),
        ),
    ]
