# Generated by Django 6.0.3 on 2026-04-22 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_project_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(upload_to='tasks/files/', verbose_name='Fayl'),
        ),
        migrations.CreateModel(
            name='TaskRejectionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('file', models.ImageField(upload_to='tasks/rejections/', verbose_name='Rasm (Skrinshot)')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_files', to='projects.task', verbose_name='Vazifa')),
            ],
            options={
                'verbose_name': 'Rad etish fayli ',
                'verbose_name_plural': 'Rad etish fayllari',
            },
        ),
    ]
