# Generated by Django 6.0.3 on 2026-04-25 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_rename_direction_position_alter_position_options_and_more'),
        ('projects', '0023_alter_taskattachment_file_taskrejectionfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='applications.position', verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='task',
            name='sprint',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sprint'),
        ),
    ]
