# Generated by Django 6.0.3 on 2026-04-26 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_task_position_task_sprint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-created_at'], 'verbose_name': "Yig'ilish ", 'verbose_name_plural': "Yig'lishlar"},
        ),
        migrations.AlterModelOptions(
            name='meetingattendance',
            options={'ordering': ['-created_at'], 'verbose_name': "Yig'ilishga qatnashish ", 'verbose_name_plural': "Yig'ilishga qatnashishlar"},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Loyiha ', 'verbose_name_plural': 'Loyihalar'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vazifa ', 'verbose_name_plural': 'Vazifalar'},
        ),
        migrations.AlterModelOptions(
            name='taskattachment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vazifa fayli ', 'verbose_name_plural': 'Vazifa fayllari'},
        ),
        migrations.AlterModelOptions(
            name='taskrejectionfile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rad etish fayli ', 'verbose_name_plural': 'Rad etish fayllari'},
        ),
    ]
