# Generated by Django 6.0.3 on 2026-04-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_alter_task_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='prefix',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Prefiksi'),
        ),
    ]
