# Generated by Django 6.0.3 on 2026-04-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_project_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='uid',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='uid',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='uid',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='UID'),
        ),
    ]
