# Generated by Django 6.0.3 on 2026-05-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_alter_meeting_uid_alter_project_uid_alter_task_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='prefix',
            field=models.CharField(default=0, max_length=50, unique=True, verbose_name='Prefiksi'),
            preserve_default=False,
        ),
    ]
