# Generated by Django 6.0.3 on 2026-05-03 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_alter_project_employees_alter_project_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='penalty_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Jarima foizi (%)'),
        ),
        migrations.AddField(
            model_name='project',
            name='was_overdue',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='was_overdue',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='payroll_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='payroll_processed',
            field=models.BooleanField(default=False),
        ),
    ]
