# Generated by Django 6.0.3 on 2026-05-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_alter_project_description_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Yashirilganmi?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='prefix',
            field=models.CharField(max_length=10, unique=True, verbose_name='Prefiksi'),
        ),
    ]
