# Generated by Django 6.0.3 on 2026-05-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_project_is_hidden_alter_project_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hidden_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
