# Generated by Django 6.0.3 on 2026-05-07 10:29

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_alter_project_testers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(upload_to='tasks/files/', validators=[apps.common.validators.validate_file_size], verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='taskrejectionfile',
            name='file',
            field=models.ImageField(upload_to='tasks/rejections/', validators=[apps.common.validators.validate_file_size], verbose_name='Rasm (Skrinshot)'),
        ),
    ]
