# Generated by Django 6.0.3 on 2026-05-07 10:56

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_alter_taskattachment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(upload_to='tasks/files/', validators=[apps.common.validators.validate_file_extension, apps.common.validators.validate_file_size], verbose_name='Fayl'),
        ),
    ]
