# Generated by Django 6.0.3 on 2026-05-07 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequest',
            name='accountant',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles__contains': ['accountant']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Hisobchi'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='expense_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_requests', to='finance.expensecategory', verbose_name='Xarajat kategoriyasi'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='projects.project', verbose_name='Loyiha'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='expensereceipt',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='finance.expenserequest', verbose_name="Xarajat so'rovi"),
        ),
        migrations.AddField(
            model_name='ledger',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.expenserequest', verbose_name='Xarajat'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='accountant',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles__contains': ['accountant']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payrolls', to=settings.AUTH_USER_MODEL, verbose_name='Hisobchi'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.payroll', verbose_name='Ish haqi'),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('user', 'month')},
        ),
    ]
