# Generated by Django 6.0.3 on 2026-04-13 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_expensecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-month'], 'verbose_name': 'Ish haqi ', 'verbose_name_plural': 'Ish haqlari'},
        ),
    ]
