# Generated by Django 6.0.3 on 2026-04-13 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_payroll_options'),
        ('projects', '0011_alter_meeting_uid_alter_task_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='projects.project', verbose_name='Loyiha'),
        ),
    ]
