# Generated by Django 6.0.3 on 2026-05-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_expensecategory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='description',
            field=models.TextField(),
        ),
    ]
