# Generated by Django 6.0.3 on 2026-05-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_ledger_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='expensereceipt',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
    ]
