# Generated by Django 6.0.3 on 2026-04-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_expenserequest_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Tasdiqlandimi?'),
        ),
    ]
