# Generated by Django 5.2.12 on 2026-08-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_alter_expensecategory_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="reason",
            field=models.TextField(blank=True, null=True, verbose_name="Sababi"),
        ),
    ]
