# Generated by Django 6.0.3 on 2026-04-15 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_payroll_is_confirmed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserequest',
            name='accountant',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles__contains': ['accountant']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Hisobchi'),
        ),
    ]
