# Generated by Django 5.2.12 on 2026-08-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_payroll_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="missed_meetings_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Qatnashilmagan majlislar soni"
            ),
        ),
    ]
