# Generated by Django 6.0.3 on 2026-04-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_expenserequest_accountant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserequest',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Karta raqam orqali')], default='card', max_length=10, verbose_name="To'lov turi"),
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='type',
            field=models.CharField(choices=[('withdrawal', "Mablag' chiqarish"), ('company', 'Kompaniya xarajatlari'), ('other', 'Boshqa xarajatlar')], default='withdrawal', max_length=20, verbose_name='Turi'),
        ),
    ]
