# Generated by Django 6.0.3 on 2026-04-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_expenserequest_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequest',
            name='uid',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True, verbose_name='UID'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='uid',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True, verbose_name='UID'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='uid',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True, verbose_name='UID'),
        ),
    ]
