# Generated by Django 6.0.3 on 2026-04-22 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_expenserequest_uid_ledger_uid_payroll_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenserequest',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='uid',
        ),
    ]
