# Generated by Django 6.0.3 on 2026-04-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_remove_expenserequest_uid_remove_ledger_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'landi"), ('confirmed', 'Tasdiqlandi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20, verbose_name='Holati'),
        ),
    ]
