# Generated by Django 6.0.3 on 2026-04-29 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_expenserequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequest',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Bekor qilish sababi'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan vaqti'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='accountant',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles__contains': ['accountant']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payrolls', to=settings.AUTH_USER_MODEL, verbose_name='Hisobchi'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqti'),
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Sababi'),
        ),
    ]
