# Generated by Django 6.0.3 on 2026-04-29 15:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_expenserequest_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Miqdori'),
        ),
    ]
