# Generated by Django 6.0.3 on 2026-05-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_expenserequest_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-month', '-id'], 'verbose_name': 'Ish haqi ', 'verbose_name_plural': 'Ish haqlari'},
        ),
    ]
