# Generated by Django 6.0.3 on 2026-05-07 10:29

import apps.common.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_payroll_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('file', models.FileField(upload_to='expense/receipts/%Y/%m/', validators=[apps.common.validators.validate_file_size], verbose_name='Chek hujjati')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='finance.expenserequest', verbose_name="Xarajat so'rovi")),
            ],
            options={
                'verbose_name': 'Xarajat cheki',
                'verbose_name_plural': 'Xarajat cheklari',
            },
        ),
    ]
