# Generated by Django 6.0.3 on 2026-05-07 10:56

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_expensereceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensereceipt',
            name='file',
            field=models.FileField(upload_to='expense/receipts/%Y/%m/', validators=[apps.common.validators.validate_file_extension, apps.common.validators.validate_file_size], verbose_name='Chek hujjati'),
        ),
    ]
