# Generated by Django 6.0.3 on 2026-05-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('title', models.CharField(max_length=255, verbose_name='Vazifa nomi')),
                ('color', models.CharField(choices=[('red', 'Qizil'), ('green', 'Yashil'), ('blue', "Ko'k"), ('yellow', 'Sariq')], default='blue', max_length=20, verbose_name='Rangi')),
                ('is_done', models.BooleanField(default=False, verbose_name='Bajarildimi?')),
            ],
            options={
                'verbose_name': 'Vazifa ',
                'verbose_name_plural': 'Vazifalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('is_done', models.BooleanField(default=False, verbose_name='Bajarildimi?')),
            ],
            options={
                'verbose_name': 'Kichik vazifa ',
                'verbose_name_plural': 'Kichik vazifalar',
                'ordering': ['created_at'],
            },
        ),
    ]
