# Generated by Django 6.0.3 on 2026-04-30 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vazifa ', 'verbose_name_plural': 'Vazifalar'},
        ),
        migrations.AddField(
            model_name='todo',
            name='color',
            field=models.CharField(choices=[('red', 'Qizil'), ('green', 'Yashil'), ('blue', "Ko'k"), ('yellow', 'Sariq')], default='blue', max_length=20, verbose_name='Rangi'),
        ),
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Muddati'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Bajarildimi?'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Vazifa nomi'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to=settings.AUTH_USER_MODEL, verbose_name='Egasi'),
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('is_done', models.BooleanField(default=False, verbose_name='Bajarildimi?')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='todos.todo', verbose_name='Vazifa')),
            ],
            options={
                'verbose_name': 'Kichik vazifa ',
                'verbose_name_plural': 'Kichik vazifalar',
                'ordering': ['created_at'],
            },
        ),
    ]
