# Generated by Django 6.0.3 on 2026-05-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_options_todo_color_todo_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='deadline',
        ),
    ]
