# Generated by Django 6.0.3 on 2026-05-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Faolmi?'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Faolmi?'),
        ),
    ]
