# Generated by Django 6.0.3 on 2026-05-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todo_created_at_alter_todo_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
    ]
