# Generated by Django 6.0.3 on 2026-04-06 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="The phone number must be in the format '+998XXXXXXXXX' and consist of 13 characters.", regex='^\\+998\\d{9}$')]),
        ),
    ]
