# Generated by Django 6.0.3 on 2026-04-07 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userstats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStats',
        ),
    ]
