# Generated by Django 6.0.5 on 2026-05-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_active_role'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE users_user 
                ALTER COLUMN card_number TYPE jsonb 
                USING CASE 
                    WHEN card_number IS NULL OR card_number = '' THEN '{}'::jsonb
                    ELSE to_jsonb(card_number)
                END;
            """,
            reverse_sql="""
                ALTER TABLE users_user 
                ALTER COLUMN card_number TYPE varchar(16);
            """
        ),

        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='user',
                    name='card_number',
                    field=models.JSONField(blank=True, default=dict, verbose_name='Karta raqami'),
                ),
            ]
        ),
    ]