# Generated by Django 6.0.5 on 2026-05-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_active_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_number',
            field=models.JSONField(blank=True, default=dict, verbose_name='Karta raqami'),
        ),
    ]
