# Generated by Django 6.0.3 on 2026-04-13 17:18

import apps.users.utils
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_direction_options_alter_region_options_and_more'),
        ('users', '0005_alter_user_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.utils.user_avatar_path, verbose_name='Xodim avatari'),
        ),
        migrations.AddField(
            model_name='user',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.direction', verbose_name="Yo'nalishi"),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.utils.passport_path, verbose_name='Passport rasmi'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_series',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Passport seriyasi va raqami'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqami +998XXXXXXXXX formatida bo'lishi kerak.", regex='^\\+998\\d{9}$')], verbose_name='Telefon raqami'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.region', verbose_name='Viloyati'),
        ),
    ]
