# Generated by Django 6.0.3 on 2026-04-15 08:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_position_user_avatar_user_direction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('superadmin', 'Bosh administrator'), ('admin', 'Administrator'), ('manager', 'Menejer'), ('employee', 'Xodim'), ('auditor', 'Nazoratchi'), ('accountant', 'Hisobchi')], max_length=20), blank=True, default=list, verbose_name='Rollari'),
        ),
    ]
