# Generated by Django 6.0.3 on 2026-04-17 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_district_application_district'),
        ('users', '0009_alter_user_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.district', verbose_name='Tumani'),
        ),
    ]
