# Generated by Django 6.0.3 on 2026-04-21 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_rename_direction_position_alter_position_options_and_more'),
        ('users', '0010_alter_user_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='direction',
            new_name='position',
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.position', verbose_name='Lavozimi'),
        ),
    ]
