# Generated by Django 6.0.3 on 2026-04-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_direction_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ijtimoiy tarmoqlar'),
        ),
    ]
