# Generated by Django 6.0.3 on 2026-04-26 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_social_links'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Foydalanuvchi ', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
    ]
