# Generated by Django 6.0.3 on 2026-04-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Bosh administrator'), ('admin', 'Administrator'), ('manager', 'Menejer'), ('employee', 'Xodim'), ('auditor', 'Nazoratchi'), ('accountant', 'Hisobchi')], max_length=20, null=True, verbose_name='Aktiv rol'),
        ),
    ]
