# Generated by Django 6.0.3 on 2026-05-07 10:29

import apps.common.validators
import apps.users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_active_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.utils.user_avatar_path, validators=[apps.common.validators.validate_file_size], verbose_name='Xodim avatari'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.utils.passport_path, validators=[apps.common.validators.validate_file_size], verbose_name='Passport rasmi'),
        ),
    ]
