# Generated by Django 6.0.3 on 2026-04-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['name'], 'verbose_name': "Yo'nalish", 'verbose_name_plural': "Yo'nalishlar"},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Viloyat', 'verbose_name_plural': 'Viloyatlar'},
        ),
        migrations.RenameField(
            model_name='direction',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='direction',
            name='is_application',
            field=models.BooleanField(default=False, verbose_name='Ariza uchun ham ishlatilsinmi?'),
        ),
        migrations.AddField(
            model_name='region',
            name='is_application',
            field=models.BooleanField(default=False, verbose_name='Ariza uchun ham ishlatilsinmi?'),
        ),
    ]
