# Generated by Django 6.0.3 on 2026-04-21 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_district_application_district'),
        ('users', '0010_alter_user_district'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Direction',
            new_name='Position',
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name'], 'verbose_name': 'Lavozim', 'verbose_name_plural': 'Lavozimlar'},
        ),
        migrations.RenameField(
            model_name='application',
            old_name='direction',
            new_name='position',
        ),
        migrations.AlterField(
            model_name='application',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='applications.position', verbose_name='Lavozim'),
        ),
    ]
