# Generated by Django 6.0.3 on 2026-04-25 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_rename_direction_position_alter_position_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='district',
        ),
        migrations.RemoveField(
            model_name='district',
            name='is_application',
        ),
    ]
