# Generated by Django 6.0.3 on 2026-05-07 11:04

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_remove_application_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to='applications/resumes/', validators=[apps.common.validators.validate_only_pdf, apps.common.validators.validate_file_size], verbose_name='Rezyume (CV)'),
        ),
    ]
