# Generated by Django 6.0.3 on 2026-05-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_created_at_alter_auditlog_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
    ]
