# Generated by Django 6.0.3 on 2026-04-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_options_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('confirm', 'Confirm'), ('restore', 'Restore')], max_length=50, verbose_name='Harakati'),
        ),
    ]
