# Generated by Django 6.0.3 on 2026-05-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tarix yozuvi ', 'verbose_name_plural': 'Tarix yozuvlari'},
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='timestamp',
        ),
    ]
