# Generated by Django 6.0.3 on 2026-04-26 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Tarix yozuvi ', 'verbose_name_plural': 'Tarix yozuvlari'},
        ),
    ]
