# Generated by Django 6.0.5 on 2026-05-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_auditlog_options_remove_auditlog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='object_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Obyekt nomi'),
        ),
    ]
