# Generated by Django 6.0.3 on 2026-04-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='device_id',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
