# Generated by Django 6.0.3 on 2026-05-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
    ]
